spring:
  datasource:
    url: jdbc:mysql://localhost:3307/baking
    username: root
    password: avengers123
  web:
    resources:
      static-locations: classpath:static

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*.xml
